name: Node.js CI

env:
  TEST: |
        pwd
        cd ..
        git clone https://github.com/neutralinojs/neutralino.js.git
        ls

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3


    - name: Test
      run: |
        echo "$TEST" > cmd.sh
        chmod +x cmd.sh
        ./cmd.sh
