name: Release
permissions:
  contents: write

on: 
  workflow_dispatch:
    inputs: 
      version: 
        type: string
        required: false
        description: "Version number Eg: 4.2.0"
        
env:
  VERSION: ${{inputs.version || 'nightly'}}

jobs:
  release-info:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout 
      uses: actions/checkout@v6
    - name: Release info 
      run: |
        echo "$VERSION"
    - name: Create a new branch for the release
      run: |
        if git ls-remote --exit-code --heads origin $VERSION; then
          git push origin -d $VERSION
        fi
        git checkout -b $VERSION
        git push origin $VERSION
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}

    - name: Create a commit
      run: |        
        file=$(( $RANDOM % 100 )).txt
        branch=branch-$file
        echo $file > $file
        git config user.name "github-actions[bot]"
        git config user.email "41898282+github-actions[bot]@users.noreply.github.com"
        git checkout -b $branch
        git add $file
        git commit -m "Add $file"
        git push origin $branch
      env:
        GH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
